const products = [
  // === ИСПАРИТЕЛИ И КАРТРИДЖИ ===
  { id: 1, name: 'Испарители Smoant Charon Baby/Battlestar 0.6', category: 'coils', price: 249, priceOpt: '249', emoji: '🔥', description: 'Совместимость: Charon Baby, Battlestar', featured: false },
  { id: 2, name: 'Испарители UDN Sharp', category: 'coils', price: 299, priceOpt: '299', emoji: '🔥', description: 'Совместимость: UDN Sharp', featured: false },
  { id: 3, name: 'Испарители Jelly Box Nano 0.5', category: 'coils', price: 299, priceOpt: '299', emoji: '🔥', description: 'Совместимость: Jelly Box Nano, Nano 2, Nano 3, XS', featured: false },
  { id: 4, name: 'Картридж Smoant Vikii 1.2', category: 'coils', price: 349, priceOpt: '349', emoji: '💨', description: 'Совместимость: Smoant Vikii', featured: false },
  { id: 5, name: 'Картриджи Voopoo Vmate 0.7 V2', category: 'coils', price: 349, priceOpt: '349', emoji: '💨', description: 'Совместимость: Vthru, Vmate Infinity, Vmate E, Vmate Pro', featured: false },
  { id: 6, name: 'Картриджи Voopoo Vmate 0.4 V2 боковая заправка', category: 'coils', price: 349, priceOpt: '349', emoji: '💨', description: 'Совместимость: Vmate I2, Vmate E2, Vmate Max, Vmate Pro', featured: false },
  { id: 7, name: 'Картридж Minifit', category: 'coils', price: 349, priceOpt: '349', emoji: '💨', description: 'Совместимость: Minifit, Minifit S, Minifit Max', featured: false },
  { id: 8, name: 'Картридж Smok Nfix 1.0', category: 'coils', price: 349, priceOpt: '349', emoji: '💨', description: 'Совместимость: Smok Nfix', featured: false },
  { id: 9, name: 'Картриджи Brusko Micool', category: 'coils', price: 349, priceOpt: '349', emoji: '💨', description: 'Совместимость: Brusko Micool', featured: false },
  { id: 10, name: 'Картридж Xros 0.6/0.8', category: 'coils', price: 349, priceOpt: '349', emoji: '💨', description: 'Совместимость: Xros 1/2/3/4/5, Mini, Nano, Pro, Cube', featured: true },
  { id: 11, name: 'Картридж Xros 0.7 боковая заправка', category: 'coils', price: 349, priceOpt: '349', emoji: '💨', description: 'Совместимость: Все Xros семейство', featured: false },
  { id: 12, name: 'Картридж Xros 0.4', category: 'coils', price: 349, priceOpt: '349', emoji: '💨', description: 'Совместимость: Xros Pro, Xros 4/4 mini, Xros 5/5 mini', featured: false },
  { id: 13, name: 'Картридж Aegis Q 0.6/0.4', category: 'coils', price: 349, priceOpt: '349', emoji: '💨', description: 'Совместимость: Aegis Q Sounder, Wenax Mini, Digi-Q', featured: false },
  { id: 14, name: 'Испаритель S-7 Coil 0.3', category: 'coils', price: 349, priceOpt: '349', emoji: '🔥', description: 'Совместимость: Charon Baby+, Santi, Knight 40, Charon T50, Pasito Pro', featured: false },
  { id: 15, name: 'Испаритель Pasito Mini 0.6', category: 'coils', price: 349, priceOpt: '349', emoji: '🔥', description: 'Совместимость: Pasito Mini', featured: false },
  { id: 16, name: 'Испаритель K-1 Smoant 0.3', category: 'coils', price: 349, priceOpt: '349', emoji: '🔥', description: 'Совместимость: Pasito 2, Knight 80, Knight Aio', featured: false },
  { id: 17, name: 'Испаритель K-4 Smoant 0.2', category: 'coils', price: 349, priceOpt: '349', emoji: '🔥', description: 'Совместимость: Pasito 2, Knight 80, Knight Aio', featured: false },
  { id: 18, name: 'Испаритель K-5 Smoant 0.15', category: 'coils', price: 349, priceOpt: '349', emoji: '🔥', description: 'Совместимость: Pasito 2, Knight 80, Knight Aio', featured: false },
  { id: 19, name: 'Картридж Brusko Minican (верх/бок/низ)', category: 'coils', price: 349, priceOpt: '349', emoji: '💨', description: 'Совместимость: всё семейство Brusko Minican', featured: false },
  { id: 20, name: 'Испаритель Manto Aio 0.15', category: 'coils', price: 349, priceOpt: '349', emoji: '🔥', description: 'Совместимость: Manto Aio 1/2, Plus 2, Pro, Ultra, Baby', featured: false },
  { id: 21, name: 'Испаритель Pasito 1 DTL 0.6', category: 'coils', price: 349, priceOpt: '349', emoji: '🔥', description: 'Совместимость: Pasito 1', featured: false },
  { id: 22, name: 'Картридж Elf Bar Elfx 0.6', category: 'coils', price: 349, priceOpt: '349', emoji: '💨', description: 'Совместимость: Elf Bar Elfx', featured: false },
  { id: 23, name: 'Картридж Plonq 0.4/0.6/0.85', category: 'coils', price: 399, priceOpt: '399', emoji: '💨', description: 'Совместимость: Plonq Meta, Plonq Meta Smart', featured: false },
  { id: 24, name: 'Испарители Vaporesso GTX 0.4/0.3/0.2', category: 'coils', price: 349, priceOpt: '349', emoji: '🔥', description: 'Совместимость: LUXE, GTX GO, TARGET, GEN NANO, XIRON и др.', featured: true },
  { id: 25, name: 'Картридж Vaporesso Osmal 1.2', category: 'coils', price: 349, priceOpt: '349', emoji: '💨', description: 'Совместимость: Osmal 1, Osmal 2', featured: false },
  { id: 26, name: 'Картриджи Vaporesso Luxe Q', category: 'coils', price: 349, priceOpt: '349', emoji: '💨', description: 'Совместимость: Luxe Q, Q2, Q3', featured: false },
  { id: 27, name: 'Испарители Voopoo PnP 0.15', category: 'coils', price: 349, priceOpt: '349', emoji: '🔥', description: 'Совместимость: Vinci, Drag X/S/Max, Navi', featured: false },
  { id: 28, name: 'Испаритель Aegis B series 0.3/0.2/0.4', category: 'coils', price: 349, priceOpt: '349', emoji: '🔥', description: 'Совместимость: Aegis Hero, Boost, H45, B60, H45 Classic', featured: false },
  { id: 29, name: 'Испаритель Aegis B 0.15', category: 'coils', price: 349, priceOpt: '349', emoji: '🔥', description: 'Совместимость: Aegis Force', featured: false },
  { id: 30, name: 'Испаритель Aegis P series 0.2/0.15', category: 'coils', price: 349, priceOpt: '349', emoji: '🔥', description: 'Совместимость: Aegis B100, E100', featured: false },
  { id: 31, name: 'Испарители Voopoo PNP-TW15 0.15', category: 'coils', price: 349, priceOpt: '349', emoji: '🔥', description: 'Совместимость: Vaporesso Swag 80, GTX go, Target, Drag, Vinci, Argus', featured: false },
  { id: 32, name: 'Картриджи Voopoo Argus', category: 'coils', price: 349, priceOpt: '349', emoji: '💨', description: 'Совместимость: все модели Argus Pod', featured: false },
  { id: 33, name: 'Картридж Vaporesso Luxe Q 0.6 3ml', category: 'coils', price: 349, priceOpt: '349', emoji: '💨', description: 'Совместимость: всё семейство Vaporesso Luxe', featured: false },
  { id: 34, name: 'Испаритель Aegis J series 0.6', category: 'coils', price: 399, priceOpt: '399', emoji: '🔥', description: 'Совместимость: Aegis Digi Max R, Aegis Digi R', featured: false },
  { id: 35, name: 'Испаритель Aegis Z Coil 0.2', category: 'coils', price: 399, priceOpt: '399', emoji: '🔥', description: 'Совместимость: все атомайзеры Aegis Zeus', featured: false },
  { id: 36, name: 'Картридж URSA 0.8A/0.6A', category: 'coils', price: 399, priceOpt: '399', emoji: '💨', description: 'Совместимость: Ursa Nano, Art, Pro, Pocket, Baby, Cap, Epouch', featured: false },
  { id: 37, name: 'Испаритель Lost Vape UB Ultra M8', category: 'coils', price: 399, priceOpt: '399', emoji: '🔥', description: 'Совместимость: Centaurus B60, B80, G80', featured: false },
  { id: 38, name: 'Испаритель Lost Vape UB Lite L7', category: 'coils', price: 399, priceOpt: '399', emoji: '🔥', description: 'Совместимость: Thelema Mini 45w, баки UB Lite Tank', featured: false },
  { id: 39, name: 'Картридж Aegis Nano 0.6', category: 'coils', price: 399, priceOpt: '399', emoji: '💨', description: 'Совместимость: Aegis Nano 1, Nano 2', featured: false },
  { id: 40, name: 'Картридж Aegis An2 0.6 (Nano 2)', category: 'coils', price: 399, priceOpt: '399', emoji: '💨', description: 'Совместимость: Aegis Nano 1, Nano 2', featured: false },
  { id: 41, name: 'Картридж Charon Racer', category: 'coils', price: 399, priceOpt: '399', emoji: '💨', description: 'Совместимость: Charon Racer', featured: false },
  { id: 42, name: 'Картридж Manto Nano Pod 0.5', category: 'coils', price: 399, priceOpt: '399', emoji: '💨', description: 'Совместимость: все модели Manto Nano', featured: false },
  { id: 43, name: 'Испарители Voopoo PNP-X 0.15', category: 'coils', price: 399, priceOpt: '399', emoji: '🔥', description: 'Совместимость: Drag S2, Drag X2', featured: false },
  { id: 44, name: 'Испаритель Voopoo TPP-DM3 0.15', category: 'coils', price: 399, priceOpt: '399', emoji: '🔥', description: 'Совместимость: Drag X Pro, S Pro, X Plus, Drag 3', featured: false },
  { id: 45, name: 'Картридж Manto Aio с золотником', category: 'coils', price: 499, priceOpt: '499', emoji: '💨', description: 'Совместимость: Manto Aio, Plus, Plus 2', featured: false },
  { id: 46, name: 'Бак Charon Baby +', category: 'coils', price: 499, priceOpt: '499', emoji: '💨', description: 'Совместимость: Charon Baby +', featured: false },
  { id: 47, name: 'Картридж Pasito Pro', category: 'coils', price: 499, priceOpt: '499', emoji: '💨', description: 'Совместимость: Smoant Pasito Pro', featured: false },
  { id: 48, name: 'Картридж Aegis H45', category: 'coils', price: 549, priceOpt: '549', emoji: '💨', description: 'Совместимость: Aegis H45', featured: false },
  { id: 49, name: 'Картридж Pasito 2/Kit', category: 'coils', price: 549, priceOpt: '549', emoji: '💨', description: 'Совместимость: Pasito 2, Pasito 2 Kit', featured: false },
  { id: 50, name: 'Картридж Aegis B100', category: 'coils', price: 549, priceOpt: '549', emoji: '💨', description: 'Совместимость: Aegis B100', featured: false },
  { id: 51, name: 'Картридж Aegis B60 / Boost 3', category: 'coils', price: 549, priceOpt: '549', emoji: '💨', description: 'Совместимость: Aegis B60, Aegis Boost 3', featured: false },
  { id: 52, name: 'Картридж Voopoo 4.5ml', category: 'coils', price: 549, priceOpt: '549', emoji: '💨', description: 'Совместимость: Drag S/X/Max, Argus, Argus Pro', featured: false },
  { id: 53, name: 'Баки Voopoo PnP X DTL', category: 'coils', price: 549, priceOpt: '549', emoji: '💨', description: 'Совместимость: Drag S2/S3, X2/X3, Argus Pro 2', featured: false },
  { id: 54, name: 'Бак Pasito 3', category: 'coils', price: 549, priceOpt: '549', emoji: '💨', description: 'Совместимость: Pasito 3', featured: false },
  { id: 55, name: 'Картридж GeekVape Aegis Hero 5 6.5ml', category: 'coils', price: 549, priceOpt: '549', emoji: '💨', description: 'Совместимость: GeekVape Aegis Hero 5', featured: false },
  { id: 56, name: 'Бак Centaurus UB Aio', category: 'coils', price: 549, priceOpt: '549', emoji: '💨', description: 'Совместимость: Centaurus B60, B80, G80', featured: false },
  { id: 57, name: 'Бак Charon T50', category: 'coils', price: 549, priceOpt: '549', emoji: '💨', description: 'Совместимость: Charon T50', featured: false },
  { id: 58, name: 'RBA Coil база', category: 'coils', price: 599, priceOpt: '599', emoji: '🔧', description: 'Совместимость: Pasito 2, Pasito 3, Knight 80, Knight Aio', featured: false },
  { id: 59, name: 'Картридж Aegis H45 со встроенным испарителем 0.4', category: 'coils', price: 599, priceOpt: '599', emoji: '💨', description: 'Совместимость: Aegis H45', featured: false },

  // === НИКОБУСТЕРЫ ===
  { id: 60, name: 'Никобустер прозрачный +30мг 1шт', category: 'accessories', price: 149, priceOpt: '149', emoji: '💧', description: 'Никобустер 30мг', featured: false },

  // === АКБ ===
  { id: 61, name: 'АКБ 18650 (огурцы/шоколадки/розовые)', category: 'accessories', price: 549, priceOpt: '549', emoji: '🔋', description: 'Аккумулятор 18650', featured: true },

  // === СИГАРЕТЫ ===
  { id: 62, name: 'Сигариллы Corsar of the Queen Original (2шт)', category: 'accessories', price: 100, priceOpt: '100', emoji: '🚬', description: 'Сигариллы с фильтром, оригинал', featured: false },
  { id: 63, name: 'Сигариллы Corsar of the Queen Ром (2шт)', category: 'accessories', price: 100, priceOpt: '100', emoji: '🚬', description: 'Сигариллы с ароматом рома', featured: false },
  { id: 64, name: 'Сигариллы Corsar of the Queen Порто (2шт)', category: 'accessories', price: 100, priceOpt: '100', emoji: '🚬', description: 'Сигариллы с ароматом портвейна', featured: false },
  { id: 65, name: 'Сигариллы Corsar of the Queen Капучино (2шт)', category: 'accessories', price: 100, priceOpt: '100', emoji: '🚬', description: 'Сигариллы с ароматом капучино', featured: false },
  { id: 66, name: 'Сигариллы Corsar of the Queen Gold (2шт)', category: 'accessories', price: 100, priceOpt: '100', emoji: '🚬', description: 'Сигариллы Gold', featured: false },
  { id: 67, name: 'Сигариллы Corsar of the Queen Кофе (2шт)', category: 'accessories', price: 100, priceOpt: '100', emoji: '🚬', description: 'Сигариллы с ароматом кофе', featured: false },

  // === УСТРОЙСТВА ===
  { id: 68, name: 'Brusko Micool', category: 'pod', price: 399, priceOpt: '399', emoji: '💨', description: 'Компактное устройство', featured: false },
  { id: 69, name: 'Brusko Nevoks Feelin 2', category: 'pod', price: 599, priceOpt: '599', emoji: '💨', description: 'Стильное устройство', featured: false },
  { id: 70, name: 'Brusko Minican Flick', category: 'pod', price: 599, priceOpt: '599', emoji: '💨', description: 'Компактная pod-система', featured: false },
  { id: 71, name: 'Lost Vape Ursa Cap', category: 'pod', price: 999, priceOpt: '999', emoji: '💨', description: 'Надёжная pod-система', featured: false },
  { id: 72, name: 'Voopoo Argus G2 Mini', category: 'pod', price: 1199, priceOpt: '1199', emoji: '💨', description: 'Миниатюрная pod-система', featured: false },
  { id: 73, name: 'Aegis Sounder Q2', category: 'pod', price: 1299, priceOpt: '1299', emoji: '💨', description: 'Защищённая pod-система', featured: false },
  { id: 74, name: 'Voopoo Vmate Mini', category: 'pod', price: 1299, priceOpt: '1299', emoji: '💨', description: 'Компактная pod-система', featured: false },
  { id: 75, name: 'Vaporesso Xros Mini', category: 'pod', price: 1499, priceOpt: '1499', emoji: '💨', description: 'Проверенная классика', featured: true },
  { id: 76, name: 'Vaporesso Xros 3 Mini', category: 'pod', price: 1699, priceOpt: '1699', emoji: '💨', description: 'Популярная pod-система', featured: true },
  { id: 77, name: 'Vaporesso Xros Cube', category: 'pod', price: 1799, priceOpt: '1799', emoji: '💨', description: 'Стильная pod-система', featured: false },
  { id: 78, name: 'Vaporesso Xros 4 Mini', category: 'pod', price: 1899, priceOpt: '1899', emoji: '💨', description: 'Новинка 2025', featured: false },
  { id: 79, name: 'Aegis Hero Q', category: 'pod', price: 1999, priceOpt: '1999', emoji: '💨', description: 'Защищённая pod-система', featured: false },
  { id: 80, name: 'Vaporesso Xros 5 Mini', category: 'pod', price: 2199, priceOpt: '2199', emoji: '💨', description: 'Новинка 2025', featured: false },
  { id: 81, name: 'Vaporesso Xros 4', category: 'pod', price: 2299, priceOpt: '2299', emoji: '💨', description: 'Продвинутая pod-система', featured: false },
  { id: 82, name: 'Vaporesso Xros 5 Mini Cool Edition', category: 'pod', price: 2299, priceOpt: '2299', emoji: '💨', description: 'Лимитированная серия', featured: false },
  { id: 83, name: 'Smoant Pasito Pro', category: 'pod', price: 2399, priceOpt: '2399', emoji: '💨', description: 'Профессиональная pod-система', featured: false },
  { id: 84, name: 'Vaporesso Xros 4 Nano', category: 'pod', price: 2499, priceOpt: '2499', emoji: '💨', description: 'Компактный Nano', featured: false },
  { id: 85, name: 'GeekVape Wenax Q Ultra', category: 'pod', price: 2599, priceOpt: '2599', emoji: '💨', description: 'Ультра-надёжная pod-система', featured: false },
  { id: 86, name: 'Plonq Meta Lite', category: 'pod', price: 2599, priceOpt: '2599', emoji: '💨', description: 'Стильная pod-система', featured: false },
  { id: 87, name: 'Smoant Pasito 2', category: 'pod', price: 2799, priceOpt: '2799', emoji: '💨', description: 'Популярная pod-система', featured: false },
  { id: 88, name: 'Vaporesso Xros 5', category: 'pod', price: 2799, priceOpt: '2799', emoji: '💨', description: 'Новинка 2025', featured: true },
  { id: 89, name: 'Smoant Pasito 2 (НОВЫЕ ЦВЕТА)', category: 'pod', price: 2899, priceOpt: '2899', emoji: '💨', description: 'Свежие расцветки', featured: false },
  { id: 90, name: 'Vaporesso Xros Pro 2', category: 'pod', price: 2899, priceOpt: '2899', emoji: '💨', description: 'Профессиональная версия', featured: false },
  { id: 91, name: 'GeekVape Aegis H45 Classic Хиро(3)', category: 'pod', price: 2899, priceOpt: '2899', emoji: '💨', description: 'Защищённая pod-система', featured: false },
  { id: 92, name: 'GeekVape Aegis H45 Classic (НОВЫЕ ЦВЕТА)', category: 'pod', price: 2999, priceOpt: '2999', emoji: '💨', description: 'Свежие расцветки', featured: false },
  { id: 93, name: 'GeekVape Aegis H45 Хиро(2) (НОВЫЕ ЦВЕТА)', category: 'pod', price: 2999, priceOpt: '2999', emoji: '💨', description: 'Классика в новых цветах', featured: false },
  { id: 94, name: 'Vaporesso Xros 5 Nano NEW', category: 'pod', price: 2999, priceOpt: '2999', emoji: '💨', description: 'Новинка 2025', featured: false },
  { id: 95, name: 'Smoant Knight 80', category: 'pod', price: 2999, priceOpt: '2999', emoji: '💨', description: 'Мощная pod-система', featured: false },
  { id: 96, name: 'GeekVape Aegis Hero 5', category: 'pod', price: 3099, priceOpt: '3099', emoji: '💨', description: 'Новейшая защищённая система', featured: false },
  { id: 97, name: 'GeekVape Aegis Boost 3', category: 'pod', price: 3199, priceOpt: '3199', emoji: '💨', description: 'Мощный под-мод', featured: false },
  { id: 98, name: 'Aegis Hero 5 Limited', category: 'pod', price: 3199, priceOpt: '3199', emoji: '💨', description: 'Лимитированная версия', featured: false },
  { id: 99, name: 'GeekVape Aegis Force', category: 'pod', price: 3299, priceOpt: '3299', emoji: '💨', description: 'Мощная система', featured: false },
  { id: 100, name: 'Smoant Knight Aio', category: 'pod', price: 3299, priceOpt: '3299', emoji: '💨', description: 'Универсальный AIO', featured: false },
  { id: 101, name: 'Plonq Meta Smart', category: 'pod', price: 3399, priceOpt: '3399', emoji: '💨', description: 'Умная pod-система', featured: false },
  { id: 102, name: 'Voopoo Vinci E120', category: 'pod', price: 3499, priceOpt: '3499', emoji: '💨', description: 'Мощный под-мод', featured: false },
  { id: 103, name: 'GeekVape Aegis B100', category: 'pod', price: 3499, priceOpt: '3499', emoji: '💨', description: 'Профессиональный мод', featured: false },
  { id: 104, name: 'Pasito 3', category: 'pod', price: 3549, priceOpt: '3549', emoji: '💨', description: 'Новейшая разработка Smoant', featured: false },
  { id: 105, name: 'GeekVape Mod Aegis S100', category: 'pod', price: 4999, priceOpt: '4999', emoji: '💨', description: 'Однобатарейный мод', featured: false },
  { id: 106, name: 'Lost Vape Centaurus G80', category: 'pod', price: 4999, priceOpt: '4999', emoji: '💨', description: 'Премиальный мод', featured: false },
  { id: 107, name: 'GeekVape Mod Aegis L200', category: 'pod', price: 5499, priceOpt: '5499', emoji: '💨', description: 'Двухбатарейный мод', featured: false },
  { id: 108, name: 'GeekVape Mod Aegis Z200', category: 'pod', price: 5499, priceOpt: '5499', emoji: '💨', description: 'Двухбатарейный мод', featured: false },
  { id: 109, name: 'Vaporesso Mod Gen 200', category: 'pod', price: 5499, priceOpt: '5499', emoji: '💨', description: 'Двухбатарейный мод', featured: false },
  { id: 110, name: 'Aegis Legend 5', category: 'pod', price: 5499, priceOpt: '5499', emoji: '💨', description: 'Новинка 2025', featured: false },
  { id: 111, name: 'Vaporesso Gen Max 220', category: 'pod', price: 5999, priceOpt: '5999', emoji: '💨', description: 'Топовый двухбатарейный мод', featured: false },

  // === ШАЙБЫ (ПАКЕТЫ С НИКОТИНОМ) ===
  { id: 112, name: 'Подушечки Podonki Critical 5mg', category: 'accessories', price: 399, priceOpt: '399', emoji: '🟤', description: 'Никотиновые подушечки Podonki Critical 5mg', featured: false },
  { id: 113, name: 'Подушечки Podonki Mad', category: 'accessories', price: 399, priceOpt: '399', emoji: '🟤', description: 'Никотиновые подушечки Podonki Mad', featured: false },
  { id: 114, name: 'Подушечки Podonki Original', category: 'accessories', price: 399, priceOpt: '399', emoji: '🟤', description: 'Никотиновые подушечки Podonki Original', featured: false },
  { id: 115, name: 'Подушечки Loop', category: 'accessories', price: 399, priceOpt: '399', emoji: '🟤', description: 'Никотиновые подушечки Loop', featured: false },
  { id: 116, name: 'ICEBERG 7mg', category: 'accessories', price: 499, priceOpt: '499', emoji: '🟤', description: 'Никотиновые подушечки ICEBERG 7mg', featured: false },
  { id: 117, name: 'Kasta 12mg', category: 'accessories', price: 499, priceOpt: '499', emoji: '🟤', description: 'Никотиновые подушечки Kasta 12mg', featured: false },
  { id: 118, name: 'Isterika 19mg', category: 'accessories', price: 549, priceOpt: '549', emoji: '🟤', description: 'Никотиновые подушечки Isterika 19mg', featured: false },
  { id: 119, name: 'Podonki Slick 17mg', category: 'accessories', price: 549, priceOpt: '549', emoji: '🟤', description: 'Никотиновые подушечки Podonki Slick 17mg', featured: false },
  { id: 120, name: 'Злая Монашка 15mg', category: 'accessories', price: 549, priceOpt: '549', emoji: '🟤', description: 'Никотиновые подушечки Злая Монашка 15mg', featured: false },
  { id: 121, name: 'Dota & Анархия 15mg', category: 'accessories', price: 549, priceOpt: '549', emoji: '🟤', description: 'Никотиновые подушечки Dota & Анархия 15mg', featured: false },
  { id: 122, name: 'Isterika & Грех 19mg', category: 'accessories', price: 549, priceOpt: '549', emoji: '🟤', description: 'Никотиновые подушечки Isterika & Грех 19mg', featured: false },
  { id: 123, name: 'Самоубийца 24mg', category: 'accessories', price: 599, priceOpt: '599', emoji: '🟤', description: 'Никотиновые подушечки Самоубийца 24mg', featured: false },
  { id: 124, name: 'Drymost 2mg', category: 'accessories', price: 599, priceOpt: '599', emoji: '🟤', description: 'Никотиновые подушечки Drymost 2mg', featured: false },

  // === ОДНОРАЗКИ ===
  { id: 125, name: 'Brusko Vini 1400 затяжек', category: 'pod', price: 299, priceOpt: '299', emoji: '💨', description: 'Одноразка Brusko Vini 1400 тяг', featured: false },
  { id: 126, name: 'Isok 4500 затяжек', category: 'pod', price: 499, priceOpt: '499', emoji: '💨', description: 'Одноразка Isok 4500 тяг', featured: false },
  { id: 127, name: 'Lost Mary OS 2600 затяжек', category: 'pod', price: 549, priceOpt: '549', emoji: '💨', description: 'Одноразка Lost Mary OS 2600 тяг', featured: false },
  { id: 128, name: 'Utbar 6000 затяжек', category: 'pod', price: 599, priceOpt: '599', emoji: '💨', description: 'Одноразка Utbar 6000 тяг', featured: false },
  { id: 129, name: 'Vdox XL 10000 затяжек', category: 'pod', price: 899, priceOpt: '899', emoji: '💨', description: 'Одноразка Vdox XL 10000 тяг', featured: false },
  { id: 130, name: 'Yooz 15000 затяжек', category: 'pod', price: 899, priceOpt: '899', emoji: '💨', description: 'Одноразка Yooz 15000 тяг', featured: false },
  { id: 131, name: 'Husky 15000 затяжек', category: 'pod', price: 999, priceOpt: '999', emoji: '💨', description: 'Одноразка Husky 15000 тяг', featured: false },
  { id: 132, name: 'Moti Go Pro 12000 затяжек', category: 'pod', price: 999, priceOpt: '999', emoji: '💨', description: 'Одноразка Moti Go Pro 12000 тяг', featured: false },
  { id: 133, name: 'Okibar 20000 затяжек', category: 'pod', price: 999, priceOpt: '999', emoji: '💨', description: 'Одноразка Okibar 20000 тяг', featured: false },
  { id: 134, name: 'Funky Lands 7000 затяжек', category: 'pod', price: 999, priceOpt: '999', emoji: '💨', description: 'Одноразка Funky Lands 7000 тяг', featured: false },
  { id: 135, name: 'Prime 12000 затяжек', category: 'pod', price: 999, priceOpt: '999', emoji: '💨', description: 'Одноразка Prime 12000 тяг', featured: false },
  { id: 136, name: 'Plonq 1200 затяжек', category: 'pod', price: 999, priceOpt: '999', emoji: '💨', description: 'Одноразка Plonq 1200 тяг', featured: false },
  { id: 137, name: 'Waka Light 8000 затяжек', category: 'pod', price: 1099, priceOpt: '1099', emoji: '💨', description: 'Одноразка Waka Light 8000 тяг', featured: false },
  { id: 138, name: 'Funky Lands DI 15000 затяжек', category: 'pod', price: 1199, priceOpt: '1199', emoji: '💨', description: 'Одноразка Funky Lands DI 15000 тяг', featured: false },
  { id: 139, name: 'Yova 7000 затяжек', category: 'pod', price: 1199, priceOpt: '1199', emoji: '💨', description: 'Одноразка Yova 7000 тяг', featured: false },
  { id: 140, name: 'Lost Mary OS 12000 с батареей', category: 'pod', price: 1299, priceOpt: '1299', emoji: '💨', description: 'Одноразка Lost Mary OS 12000 + 🔋', featured: false },
  { id: 141, name: 'Funky Lands Lander набор картридж + устройство 20000 тяг', category: 'pod', price: 1299, priceOpt: '1299', emoji: '💨', description: 'Сменная система Funky Lands Lander 20000 тяг', featured: false },
  { id: 142, name: 'Inflave Omega 10000 затяжек', category: 'pod', price: 1399, priceOpt: '1399', emoji: '💨', description: 'Одноразка Inflave Omega 10000 тяг', featured: false },
  { id: 143, name: 'Waka Xland 15000 затяжек', category: 'pod', price: 1399, priceOpt: '1399', emoji: '💨', description: 'Одноразка Waka Xland 15000 тяг', featured: false },
  { id: 144, name: 'PuffMi Dura 9000 затяжек', category: 'pod', price: 1399, priceOpt: '1399', emoji: '💨', description: 'Одноразка PuffMi Dura 9000 тяг', featured: false },
  { id: 145, name: 'Voopoo 40000 затяжек', category: 'pod', price: 1399, priceOpt: '1399', emoji: '💨', description: 'Одноразка Voopoo 40000 тяг', featured: false },
  { id: 146, name: 'Vozol Gear Power 20000 затяжек + 🔋', category: 'pod', price: 1499, priceOpt: '1499', emoji: '💨', description: 'Одноразка Vozol Gear Power 20000 тяг', featured: false },
  { id: 147, name: 'Vozol Vista 20000 затяжек', category: 'pod', price: 1499, priceOpt: '1499', emoji: '💨', description: 'Одноразка Vozol Vista 20000 тяг', featured: false },
  { id: 148, name: 'Рик и Морти 20000 затяжек', category: 'pod', price: 1499, priceOpt: '1499', emoji: '💨', description: 'Одноразка Рик и Морти 20000 тяг', featured: false },
  { id: 149, name: 'Vaporesso Dojo Imate X 40000 затяжек', category: 'pod', price: 1499, priceOpt: '1499', emoji: '💨', description: 'Одноразка Vaporesso Dojo Imate X 40000 тяг', featured: false },
  { id: 150, name: 'Plonq 4000 затяжек', category: 'pod', price: 1499, priceOpt: '1499', emoji: '💨', description: 'Одноразка Plonq 4000 тяг', featured: false },
  { id: 151, name: 'Plonq 6000 затяжек', category: 'pod', price: 1599, priceOpt: '1599', emoji: '💨', description: 'Одноразка Plonq 6000 тяг', featured: false },
  { id: 152, name: 'Podonki Last Hap 20000 затяжек + 🔋', category: 'pod', price: 1599, priceOpt: '1599', emoji: '💨', description: 'Одноразка Podonki Last Hap 20000 тяг', featured: false },
  { id: 153, name: 'PuffMi Flora 25000 затяжек', category: 'pod', price: 1699, priceOpt: '1699', emoji: '💨', description: 'Одноразка PuffMi Flora 25000 тяг (сумочка)', featured: false },
  { id: 154, name: 'Ignite 16000 затяжек', category: 'pod', price: 1699, priceOpt: '1699', emoji: '💨', description: 'Одноразка Ignite 16000 тяг', featured: false },
  { id: 155, name: 'Plonq 8000 затяжек', category: 'pod', price: 1699, priceOpt: '1699', emoji: '💨', description: 'Одноразка Plonq 8000 тяг', featured: false },
  { id: 156, name: 'Waka 20000 затяжек', category: 'pod', price: 1799, priceOpt: '1799', emoji: '💨', description: 'Одноразка Waka 20000 тяг', featured: false },
  { id: 157, name: 'Puffmi Dura 18000 затяжек', category: 'pod', price: 1799, priceOpt: '1799', emoji: '💨', description: 'Одноразка Puffmi Dura 18000 тяг', featured: false },
  { id: 158, name: 'Elf Bar Moonnight 25000 затяжек', category: 'pod', price: 1799, priceOpt: '1799', emoji: '💨', description: 'Одноразка Elf Bar Moonnight 25000 тяг', featured: false },
  { id: 159, name: 'Inflave Flex 12000 затяжек', category: 'pod', price: 1799, priceOpt: '1799', emoji: '💨', description: 'Одноразка Inflave Flex 12000 тяг', featured: false },
  { id: 160, name: 'Картридж Lost Mary X-Link (разные вкусы)', category: 'pod', price: 999, priceOpt: '999', emoji: '💨', description: 'Сменный картридж Lost Mary X-Link', featured: false },
  { id: 161, name: 'Lost Mary X-Link 20000 затяжек', category: 'pod', price: 1899, priceOpt: '1899', emoji: '💨', description: 'Сменная система Lost Mary X-Link 20000 тяг', featured: false },
  { id: 162, name: 'Plonq 12000 затяжек', category: 'pod', price: 1899, priceOpt: '1899', emoji: '💨', description: 'Одноразка Plonq 12000 тяг', featured: false },
  { id: 163, name: 'Lost Mary Combo 20000 затяжек (2 вкуса, переключатель)', category: 'pod', price: 1999, priceOpt: '1999', emoji: '💨', description: 'Одноразка Lost Mary Combo с переключателем + 🔋', featured: false },
  { id: 164, name: 'Lost Mary MO 30000 затяжек', category: 'pod', price: 1999, priceOpt: '1999', emoji: '💨', description: 'Одноразка Lost Mary MO 30000 тяг', featured: false },
  { id: 165, name: 'Rick And Morty Bad Trip 25000 затяжек', category: 'pod', price: 1999, priceOpt: '1999', emoji: '💨', description: 'Одноразка Rick And Morty Bad Trip 25000 тяг', featured: false },
  { id: 166, name: 'Vozol Rave Pro 56000 затяжек', category: 'pod', price: 1999, priceOpt: '1999', emoji: '💨', description: 'Одноразка Vozol Rave Pro 56000 тяг', featured: false },
  { id: 167, name: 'Plonq Prime 12000 затяжек', category: 'pod', price: 1999, priceOpt: '1999', emoji: '💨', description: 'Одноразка Plonq Prime 12000 тяг', featured: false },
  { id: 168, name: 'Roqy 20000 by Plonq', category: 'pod', price: 1999, priceOpt: '1999', emoji: '💨', description: 'Одноразка Roqy 20000 от Plonq', featured: false },
  { id: 169, name: 'Ignite 25000 затяжек', category: 'pod', price: 2299, priceOpt: '2299', emoji: '💨', description: 'Одноразка Ignite 25000 тяг', featured: false },
  { id: 170, name: 'Waka ET 35000 затяжек', category: 'pod', price: 2299, priceOpt: '2299', emoji: '💨', description: 'Одноразка Waka ET 35000 тяг', featured: false },
  { id: 171, name: 'Vozol Star 46000 затяжек', category: 'pod', price: 2299, priceOpt: '2299', emoji: '💨', description: 'Одноразка Vozol Star 46000 тяг', featured: false },
  { id: 172, name: 'Puffmi Mosh 40000 затяжек', category: 'pod', price: 2399, priceOpt: '2399', emoji: '💨', description: 'Одноразка Puffmi Mosh 40000 тяг', featured: false },
  { id: 173, name: 'Pafos 20000 затяжек', category: 'pod', price: 2399, priceOpt: '2399', emoji: '💨', description: 'Одноразка Pafos 20000 тяг', featured: false },
  { id: 174, name: 'Ignite 35000 затяжек', category: 'pod', price: 2399, priceOpt: '2399', emoji: '💨', description: 'Одноразка Ignite 35000 тяг', featured: false },

  // === ЖИДКОСТИ ===
  { id: 175, name: 'Жидкость Lost Lary', category: 'liquid', price: 299, priceOpt: '299', emoji: '🍬', description: 'Жидкость 10ml', featured: false },
  { id: 176, name: 'Premium Bad Trip (10ml)', category: 'liquid', price: 349, priceOpt: '349', emoji: '🍬', description: 'Премиальная жидкость 10ml', featured: false },
  { id: 177, name: 'Жидкость Duall', category: 'liquid', price: 399, priceOpt: '399', emoji: '🍬', description: 'Качественная жидкость', featured: false },
  { id: 178, name: 'Жидкость Malasian', category: 'liquid', price: 399, priceOpt: '399', emoji: '🍬', description: 'Малазийская жидкость', featured: false },
  { id: 179, name: 'Жидкость Laiska', category: 'liquid', price: 399, priceOpt: '399', emoji: '🍬', description: 'Жидкость Laiska', featured: false },
  { id: 180, name: 'Жидкость Bryzgi', category: 'liquid', price: 399, priceOpt: '399', emoji: '🍬', description: 'Жидкость Bryzgi', featured: false },
  { id: 181, name: 'Жидкость Skala', category: 'liquid', price: 449, priceOpt: '449', emoji: '🍬', description: 'Жидкость Skala', featured: false },
  { id: 182, name: 'Жидкость Narcoz', category: 'liquid', price: 449, priceOpt: '449', emoji: '🍬', description: 'Жидкость Narcoz', featured: false },
  { id: 183, name: 'Жидкость Podonki Podgon', category: 'liquid', price: 449, priceOpt: '449', emoji: '🍬', description: 'Жидкость Podonki Podgon', featured: false },
  { id: 184, name: 'Yummy Classic', category: 'liquid', price: 449, priceOpt: '449', emoji: '🍬', description: 'Жидкость Yummy Classic', featured: false },
  { id: 185, name: 'Yummy Ice', category: 'liquid', price: 449, priceOpt: '449', emoji: '🍬', description: 'Жидкость Yummy Ice', featured: false },
  { id: 186, name: 'Yummy Sour', category: 'liquid', price: 449, priceOpt: '449', emoji: '🍬', description: 'Жидкость Yummy Sour', featured: false },
  { id: 187, name: 'Жидкость Trava', category: 'liquid', price: 449, priceOpt: '449', emoji: '🍬', description: 'Жидкость Trava', featured: false },
  { id: 188, name: 'Podonki Malasian V3', category: 'liquid', price: 449, priceOpt: '449', emoji: '🍬', description: 'Podonki Malasian V3', featured: false },
  { id: 189, name: 'Hotspot Ice', category: 'liquid', price: 449, priceOpt: '449', emoji: '🍬', description: 'Жидкость Hotspot Ice', featured: false },
  { id: 190, name: 'Blood Hard', category: 'liquid', price: 449, priceOpt: '449', emoji: '🍬', description: 'Жидкость Blood Hard', featured: false },
  { id: 191, name: 'Gang', category: 'liquid', price: 499, priceOpt: '499', emoji: '🍬', description: 'Жидкость Gang', featured: false },
  { id: 192, name: 'Злая Лабуба', category: 'liquid', price: 499, priceOpt: '499', emoji: '🍬', description: 'Жидкость Злая Лабуба', featured: false },
  { id: 193, name: 'MAD', category: 'liquid', price: 499, priceOpt: '499', emoji: '🍬', description: 'Жидкость MAD', featured: false },
  { id: 194, name: 'Catswill', category: 'liquid', price: 499, priceOpt: '499', emoji: '🍬', description: 'Жидкость Catswill', featured: false },
  { id: 195, name: 'Catswill Sour', category: 'liquid', price: 499, priceOpt: '499', emoji: '🍬', description: 'Жидкость Catswill Sour', featured: false },
  { id: 196, name: 'Podonki Sour', category: 'liquid', price: 499, priceOpt: '499', emoji: '🍬', description: 'Podonki Sour', featured: false },
  { id: 197, name: 'Podonki Isterika', category: 'liquid', price: 499, priceOpt: '499', emoji: '🍬', description: 'Podonki Isterika', featured: false },
  { id: 198, name: 'Podonki Alfa', category: 'liquid', price: 499, priceOpt: '499', emoji: '🍬', description: 'Podonki Alfa', featured: false },
  { id: 199, name: 'Podonki Last Hap', category: 'liquid', price: 499, priceOpt: '499', emoji: '🍬', description: 'Podonki Last Hap', featured: false },
  { id: 200, name: 'Overmuch', category: 'liquid', price: 499, priceOpt: '499', emoji: '🍬', description: 'Жидкость Overmuch', featured: false },
  { id: 201, name: 'Podonki V1/V2', category: 'liquid', price: 499, priceOpt: '499', emoji: '🍬', description: 'Podonki V1/V2', featured: false },
  { id: 202, name: 'Podonki Vintage', category: 'liquid', price: 499, priceOpt: '499', emoji: '🍬', description: 'Podonki Vintage', featured: false },
  { id: 203, name: 'Duall Extreme', category: 'liquid', price: 499, priceOpt: '499', emoji: '🍬', description: 'Duall Extreme', featured: false },
  { id: 204, name: 'Рик и Морти На замерзоне', category: 'liquid', price: 499, priceOpt: '499', emoji: '🍬', description: 'Рик и Морти жидкость', featured: false },
  { id: 205, name: 'Рик и Морти На замерзоне Кислые', category: 'liquid', price: 499, priceOpt: '499', emoji: '🍬', description: 'Рик и Морти кислая серия', featured: false },
  { id: 206, name: 'Dota Cats', category: 'liquid', price: 499, priceOpt: '499', emoji: '🍬', description: 'Жидкость Dota Cats', featured: false },
  { id: 207, name: 'Podonki Critical', category: 'liquid', price: 549, priceOpt: '549', emoji: '🍬', description: 'Podonki Critical', featured: false },
  { id: 208, name: 'Isterika & Грех', category: 'liquid', price: 549, priceOpt: '549', emoji: '🍬', description: 'Isterika & Грех жидкость', featured: false },
  { id: 209, name: 'Rick And Morty The Anime', category: 'liquid', price: 549, priceOpt: '549', emoji: '🍬', description: 'Rick And Morty The Anime жидкость', featured: false },
  { id: 210, name: 'Catswill Extra Hard', category: 'liquid', price: 549, priceOpt: '549', emoji: '🍬', description: 'Catswill Extra Hard', featured: false },
  { id: 211, name: 'Annima Love Toyz Sour', category: 'liquid', price: 549, priceOpt: '549', emoji: '🍬', description: 'Новинка Annima Love Toyz Sour', featured: false },
  { id: 212, name: 'Rick And Morty Bad Acid', category: 'liquid', price: 549, priceOpt: '549', emoji: '🍬', description: 'Rick And Morty Bad Acid', featured: false },
  { id: 213, name: 'Black Jack 3mg щелочь табачка', category: 'liquid', price: 599, priceOpt: '599', emoji: '🍬', description: 'Табачная жидкость 3mg щелочь', featured: false },
  { id: 214, name: 'Злая Милфа', category: 'liquid', price: 599, priceOpt: '599', emoji: '🍬', description: 'Жидкость Злая Милфа', featured: false },
  { id: 215, name: 'Злая Милфа кислая', category: 'liquid', price: 599, priceOpt: '599', emoji: '🍬', description: 'Злая Милфа кислая', featured: false },
  { id: 216, name: 'Rick And Morty & Catswill NEW', category: 'liquid', price: 599, priceOpt: '599', emoji: '🍬', description: 'НОВИНКА коллаборация', featured: false },
  { id: 217, name: 'Убивашка Ultra Hard', category: 'liquid', price: 649, priceOpt: '649', emoji: '🍬', description: 'Убивашка Ultra Hard', featured: false },
  { id: 218, name: 'Злая Монашка Sweet', category: 'liquid', price: 699, priceOpt: '699', emoji: '🍬', description: 'НОВИНКА Злая Монашка Sweet', featured: false },
  { id: 219, name: 'Самоубийца V2 Acid', category: 'liquid', price: 699, priceOpt: '699', emoji: '🍬', description: 'Самоубийца V2 Acid', featured: false },
  { id: 220, name: 'Злая Монашка Black', category: 'liquid', price: 699, priceOpt: '699', emoji: '🍬', description: 'Злая Монашка Black', featured: false },
  { id: 221, name: 'ICE FOX PREMIUM by ICEBERG', category: 'liquid', price: 749, priceOpt: '749', emoji: '🍬', description: 'Премиум жидкость ICE FOX от ICEBERG', featured: false },
];

